# Generated by Django 3.2 on 2021-07-13 19:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Nikon', 'Nikon'), ('Red Camera', 'Red Camera'), ('canon', 'canon'), ('Fuji', 'Fuji'), ('Sony', 'Sony'), ('others', 'others'), ('Panasonic', 'Panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Documantry', 'Documentary'), ('Programing', 'Programing'), ('Tutorials', 'Tutorials'), ('Movie', 'Movie'), ('Music', 'Music & Songs'), ('Comedy', 'Comedy'), ('Motivation', 'Motivation'), ('Mobile_Review', 'Mobile Review')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Small', 'Small'), ('Large', 'Large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
